[package]
name = "approx_derive"
version = "0.1.0"
authors = ["Tyler Reisinger <reisinger.tyler@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
approx = "0.3.1"
proc-macro2 = "0.4"

[dependencies.syn]
version = "0.15"
features = ["full", "extra-traits"]