[package]
name = "approx_derive"
version = "0.1.0"
authors = ["Tyler Reisinger <reisinger.tyler@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
approx = "0.3.1"
proc-macro2 = "1.0"

[dependencies.syn]
version = "1.0"
features = ["full", "extra-traits"]
